'use client';

import { useEffect, useRef, useState, useCallback } from 'react';
import { Vehicle, Route, Alert, MetricSnapshot } from '@/types/tracking';
import { TrackingEngine } from '@/services/tracking/tracking-engine';
import { AlertEngine } from '@/services/tracking/alert-engine';
import { generateVehiclePool } from '@/services/tracking/vehicle-generator';
import { initializeRoutes } from '@/services/tracking/mock-routes';

export interface UseRealtimeTrackingReturn {
  vehicles: Vehicle[];
  alerts: Alert[];
  metrics: MetricSnapshot;
  isSimulating: boolean;
  simulationSpeed: number;
  startSimulation: () => void;
  stopSimulation: () => void;
  setSimulationSpeed: (speed: number) => void;
  resetSimulation: () => void;
  resolveAlert: (alertId: string) => void;
}

const DEFAULT_SIMULATION_INTERVAL = 1000; // 1 second per tick

export const useRealtimeTracking = (): UseRealtimeTrackingReturn => {
  const engineRef = useRef<TrackingEngine | null>(null);
  const alertEngineRef = useRef<AlertEngine | null>(null);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);

  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [metrics, setMetrics] = useState<MetricSnapshot>({
    activeVehicles: 0,
    routesInProgress: 0,
    routesCompleted: 0,
    delayedPickups: 0,
    averageEfficiency: 0,
    totalDistanceCovered: 0,
    timestamp: Date.now(),
  });
  const [isSimulating, setIsSimulating] = useState(false);
  const [simulationSpeed, setSimulationSpeed] = useState(1);

  /**
   * Initialize tracking engine and vehicles
   */
  useEffect(() => {
    const initialVehicles = generateVehiclePool(15);
    const routes = initializeRoutes();

    engineRef.current = new TrackingEngine(initialVehicles, routes);
    alertEngineRef.current = new AlertEngine();

    // Process initial alerts generated by constructor
    const initialAlerts = engineRef.current.getAlerts(true);
    for (const alert of initialAlerts) {
      alertEngineRef.current.addAlert(alert);
    }

    setVehicles(initialVehicles);
    setAlerts(alertEngineRef.current.getActiveAlerts());
    setMetrics(engineRef.current.getMetrics());
  }, []);

  /**
   * Simulation update loop
   */
  const updateSimulation = useCallback(() => {
    if (!engineRef.current || !alertEngineRef.current) return;

    // Update vehicle positions and states
    engineRef.current.updateSimulation();

    // Get updated state
    const updatedVehicles = engineRef.current.getVehicles();
    const engineAlerts = engineRef.current.getAlerts(true);

    // Process new alerts through alert engine
    for (const alert of engineAlerts) {
      if (!alertEngineRef.current.getActiveAlerts().find(a => a.id === alert.id)) {
        alertEngineRef.current.addAlert(alert);
      }
    }

    // Update UI state
    setVehicles([...updatedVehicles]);
    setAlerts(alertEngineRef.current.getActiveAlerts());
    setMetrics(engineRef.current.getMetrics());
  }, []);

  /**
   * Declarative Effect to handle simulation intervals
   */
  useEffect(() => {
    if (!isSimulating) {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
      return;
    }

    if (intervalRef.current) {
      clearInterval(intervalRef.current);
    }

    intervalRef.current = setInterval(() => {
      updateSimulation();
    }, DEFAULT_SIMULATION_INTERVAL / simulationSpeed);

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
    };
  }, [isSimulating, simulationSpeed, updateSimulation]);

  /**
   * Start simulation
   */
  const startSimulation = useCallback(() => {
    setIsSimulating(true);
  }, []);

  /**
   * Stop simulation
   */
  const stopSimulation = useCallback(() => {
    setIsSimulating(false);
  }, []);

  /**
   * Update simulation speed
   */
  const handleSetSimulationSpeed = useCallback(
    (speed: number) => {
      setSimulationSpeed(speed);
      if (engineRef.current) {
        engineRef.current.setSimulationSpeed(speed);
      }
    },
    []
  );

  /**
   * Reset simulation
   */
  const resetSimulation = useCallback(() => {
    setIsSimulating(false);

    if (engineRef.current) {
      engineRef.current.resetSimulation();
    }
    if (alertEngineRef.current) {
      alertEngineRef.current.clearAlerts();
    }

    setVehicles(engineRef.current?.getVehicles() || []);
    setAlerts([]);
    setMetrics(engineRef.current?.getMetrics() || {
      activeVehicles: 0,
      routesInProgress: 0,
      routesCompleted: 0,
      delayedPickups: 0,
      averageEfficiency: 0,
      totalDistanceCovered: 0,
      timestamp: Date.now(),
    });
  }, [stopSimulation]);

  /**
   * Resolve alert
   */
  const resolveAlert = useCallback((alertId: string) => {
    if (alertEngineRef.current) {
      alertEngineRef.current.resolveAlert(alertId);
      setAlerts(alertEngineRef.current.getActiveAlerts());
    }
    if (engineRef.current) {
      engineRef.current.resolveAlert(alertId);
      // Re-fetch updated vehicles array immediately so UI reflects cleared deviation state
      setVehicles([...engineRef.current.getVehicles()]);
    }
  }, []);

  /**
   * Cleanup on unmount
   */
  useEffect(() => {
    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
      }
    };
  }, []);

  return {
    vehicles,
    alerts,
    metrics,
    isSimulating,
    simulationSpeed,
    startSimulation,
    stopSimulation,
    setSimulationSpeed: handleSetSimulationSpeed,
    resetSimulation,
    resolveAlert,
  };
};
